config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#home'

  # Navigation
  get '/home' => 'static_pages#home'
  get '/login' => 'sessions#new'
  get '/about' => 'static_pages#about'
  get '/userhome' => 'static_pages#userhome'

  # Authentication
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy' 

  # User management
  get '/users' => 'users#index'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  get '/users/edit' => 'users#edit'
  post '/users/edit' => 'users#update'

  # Manager management
  get '/managers' => 'managers#index'
  get '/managers/new' => 'managers#new'
  post '/managers/new' => 'managers#create'
  get '/managers/edit' => 'managers#edit'
  post '/managers/edit' => 'managers#update'

  # Boatlog management
  #get '/boatlogs' => 'boatlogs#index'
  post '/boatlogs/:id' => 'boatlogs#show'
  #get '/boatlogs/new' => 'boatlogs#new'
  #post '/boatlogs/new' => 'boatlogs#create'
  #get '/boatlogs/edit' => 'boatlogs#edit'
  #post '/boatlogs/edit' => 'boatlogs#update'

  # Dashboard
  get '/dashboard' => 'dashboard#show'

  # Field Progress
  get '/sites' => 'sites#index'
  post '/sites/:id' => 'sites#show'

  # Surveys
  post '/fish_transects/:id' => 'fish_transects#show'
  get '/diademas' => 'diademas#index'
  get '/e_plots' => 'e_plots#index'
  get '/e_plot_corals' => 'e_plot_corals#index'
  get '/e_esa_pas' => 'e_esa_pas#index'

  # IDs
  get '/coral_codes' => 'coral_codes#index'

  # Resources
  resources :users
  resources :managers
  resources :boatlogs
  resources :sites
  resources :fish_transects
  resources :fish_rovers
  resources :algae_heights
  resources :coral_healths
  resources :e_boatlogs
  resources :e_surveys

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :require_manager

	# View all entered data
	def show
		@diademas = Diadema.all

		@data_by_divers = {}
		@divers = User.where(active: "true")

		@divers.each do |diver|
			if !@data_by_divers.has_key?(diver)
				@data_by_divers[diver] = {
					"boat" => 0,
          "boatfish" => 0,
					"ftrans" => 0,
					"frove" => 0,
					"chealth" => 0,
					"aheight" => 0
				}
			end
			@data_by_divers[diver]["boat"] += diver.boatlog_surveys.count
      @data_by_divers[diver]["boatfish"] += diver.boatlog_surveys.where(survey_type_id: SurveyType.where(category: "fish").ids).count
			@data_by_divers[diver]["ftrans"] += diver.fish_transects.count
			@data_by_divers[diver]["frove"] += diver.fish_rovers.count
			@data_by_divers[diver]["chealth"] += diver.coral_healths.count
			@data_by_divers[diver]["aheight"] += diver.algae_heights.count
		end
	  @data_by_divers = @data_by_divers.sort_by { |diver, data| diver.name }

		respond_to do |format|
			format.html # show.html.erb
		end
	end
end

app/views/dashboard/show.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <%= button_to('Boatlogs', boatlogs_path, :method => "get", :class => 'btn btn-sm btn-primary') %>
      <%= button_to('Fish Transects', fish_transects_path, :method => "get", :class => 'btn btn-sm btn-primary') %>
      <%= button_to('Fish Rovers', fish_rovers_path, :method => "get", :class => 'btn btn-sm btn-primary') %>
      <%= button_to('Coral Health', '/coral_healths', :method => "get", :class => 'btn btn-sm btn-primary') %>
      <%= button_to('Algae Heights', '/algae_heights', :method => "get", :class => 'btn btn-sm btn-primary') %>
    </div>
    <div class="row">
      <div class="span4">
        <table class="table table-striped table-bordered table-condensed">
          <thead>
            <tr>
              <th>Diver</th>
              <th>Boatlog Count</th>
              <th>Boatlog Fish Count</th>
              <th>Fish Transect Count</th>
              <th>Fish Rover Count</th>
              <th>Coral Health Count</th>
              <th>Algae Heights Count</th>
            </tr>
          </thead>
          <tbody>
            <% @data_by_divers.each do |diver, value| %>
              <tr>
                <td> <%= diver.name %></td>
                <td> <%= value["boat"] %></td>
                <td> <%= value["boatfish"] %></td>
                <td> <%= value["ftrans"] %></td>
                <td> <%= value["frove"] %></td>
                <td> <%= value["chealth"] %></td>
                <td> <%= value["aheight"] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>