config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#home'

  # Navigation
  get '/home' => 'static_pages#home'
  get '/login' => 'sessions#new'
  get '/about' => 'static_pages#about'
  get '/userhome' => 'static_pages#userhome'

  # Authentication
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy' 

  # User management
  get '/users' => 'users#index'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  get '/users/edit' => 'users#edit'
  post '/users/edit' => 'users#update'

  # Manager management
  get '/managers' => 'managers#index'
  get '/managers/new' => 'managers#new'
  post '/managers/new' => 'managers#create'
  get '/managers/edit' => 'managers#edit'
  post '/managers/edit' => 'managers#update'

  # Boatlog management
  #get '/boatlogs' => 'boatlogs#index'
  post '/boatlogs/:id' => 'boatlogs#show'
  #get '/boatlogs/new' => 'boatlogs#new'
  #post '/boatlogs/new' => 'boatlogs#create'
  #get '/boatlogs/edit' => 'boatlogs#edit'
  #post '/boatlogs/edit' => 'boatlogs#update'

  # Dashboard
  get '/dashboard' => 'dashboard#show'

  # Field Progress
  get '/sites' => 'sites#index'
  post '/sites/:id' => 'sites#show'

  # Surveys
  post '/fish_transects/:id' => 'fish_transects#show'
  get '/diademas' => 'diademas#index'
  get '/e_plots' => 'e_plots#index'
  get '/e_plot_corals' => 'e_plot_corals#index'
  get '/e_esa_pas' => 'e_esa_pas#index'

  # IDs
  get '/coral_codes' => 'coral_codes#index'

  # Resources
  resources :users
  resources :managers
  resources :boatlogs
  resources :sites
  resources :fish_transects
  resources :fish_rovers
  resources :algae_heights
  resources :coral_healths
  resources :e_boatlogs
  resources :e_surveys

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/e_plot.rb
require 'csv'

class EPlot < ApplicationRecord
	validates_presence_of :e_survey, :plot

	belongs_to :e_survey
	accepts_nested_attributes_for :e_survey

	has_many :e_plot_corals, :dependent => :destroy, inverse_of: :e_plot
  accepts_nested_attributes_for :e_plot_corals, :reject_if => :all_blank, :allow_destroy => true

  def self.as_csv
    columns = %w(fid proofed date_completed diver buddy team role habitat plot hardbottom coral_cover max_vert_relief_cm min_depth max_depth notes)
    CSV.generate(headers: true) do |csv|
      csv << columns.map(&:humanize)
      all.each do |p|
        esurv = p.e_survey
        diver = esurv.user
        csv << [esurv.fid, esurv.proofed, esurv.date_completed, diver.name, esurv.buddy, esurv.team, esurv.role, esurv.habitat, p.plot, p.hardbottom, p.coral_cover, p.max_relief_cm, p.min_depth, p.max_depth, esurv.notes]
      end
    end
  end
end

app/controllers/e_plots_controller.rb
class EPlotsController < ApplicationController
	before_action :require_user

	# View all of a user's plots
	def index
    if @current_user.manager?
      @eps = EPlot.all
      @filename = "all"
    else
      @eps = @current_user.e_surveys.e_plots.all
      @filename = @current_user.name
    end

    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data @eps.as_csv, filename: "ECMP_Abiotic_#{@filename}_#{Date.today}.csv" }
    end
	end
end

app/views/e_plots/index.html.erb
<div class="main">
  <div class="container">
    <%= button_to "Back to ECMP surveys", '/e_surveys', method: :get %>
    <%= button_to "Export CSV", e_plots_path(:format => :csv), method: :get %>
    <h1>ECMP Plots Abiotic</h1>
    <table class="display table table-striped table-condensed table-sortable">
      <thead>
        <% #print table header %>
        <tr>
          <th>FID</th>
          <th>Date</th>
          <th>Diver</th>
          <th>Team</th>
          <th>Role</th>
          <th>Plot</th>
          <th>% Hardbottom</th>
          <th>% Coral Cover</th>
          <th>Max Relief<br>(cm)</th>
          <th>Min Depth (ft)</th>
          <th>Max Depth (ft)</th>
        </tr>
      </thead>
      <tbody>
        <% #print table fields %>
        <% @eps.each do |ep| %>
          <tr>
            <td><%= ep.e_survey.fid %></td>
            <td><%= ep.e_survey.date_completed %></td>
            <td><%= ep.e_survey.user.name %></td>
            <td><%= ep.e_survey.team %></td>
            <td><%= ep.e_survey.role %></td>
            <td><%= ep.plot %></td>
            <td><%= ep.hardbottom %></td>
            <td><%= ep.coral_cover %></td>
            <td><%= ep.max_relief_cm %></td>
            <td><%= ep.min_depth %></td>
            <td><%= ep.max_depth %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>