config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#home'

  # Navigation
  get '/home' => 'static_pages#home'
  get '/login' => 'sessions#new'
  get '/about' => 'static_pages#about'
  get '/userhome' => 'static_pages#userhome'

  # Authentication
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy' 

  # User management
  get '/users' => 'users#index'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  get '/users/edit' => 'users#edit'
  post '/users/edit' => 'users#update'

  # Manager management
  get '/managers' => 'managers#index'
  get '/managers/new' => 'managers#new'
  post '/managers/new' => 'managers#create'
  get '/managers/edit' => 'managers#edit'
  post '/managers/edit' => 'managers#update'

  # Boatlog management
  #get '/boatlogs' => 'boatlogs#index'
  post '/boatlogs/:id' => 'boatlogs#show'
  #get '/boatlogs/new' => 'boatlogs#new'
  #post '/boatlogs/new' => 'boatlogs#create'
  #get '/boatlogs/edit' => 'boatlogs#edit'
  #post '/boatlogs/edit' => 'boatlogs#update'

  # Dashboard
  get '/dashboard' => 'dashboard#show'

  # Field Progress
  get '/sites' => 'sites#index'
  post '/sites/:id' => 'sites#show'

  # Surveys
  post '/fish_transects/:id' => 'fish_transects#show'
  get '/diademas' => 'diademas#index'
  get '/e_plots' => 'e_plots#index'
  get '/e_plot_corals' => 'e_plot_corals#index'
  get '/e_esa_pas' => 'e_esa_pas#index'

  # IDs
  get '/coral_codes' => 'coral_codes#index'

  # Resources
  resources :users
  resources :managers
  resources :boatlogs
  resources :sites
  resources :fish_transects
  resources :fish_rovers
  resources :algae_heights
  resources :coral_healths
  resources :e_boatlogs
  resources :e_surveys

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/e_boatlog.rb
require 'csv'

class EBoatlog < ApplicationRecord
	validates_presence_of :fid, :date_completed

	has_many :e_boatlog_teams, :dependent => :destroy, inverse_of: :e_boatlog
	accepts_nested_attributes_for :e_boatlog_teams, :reject_if => :all_blank, :allow_destroy => true

	def self.as_csv
    columns = %w(fid date_completed captain dod latitude longitude team role name time_in time_out depth_ft hss disease notes)
    CSV.generate(headers: true) do |csv|
      csv << columns.map(&:humanize)
      all.each do |ebl|
        ebl.e_boatlog_teams.each do |eblt|
          user = eblt.user
          # csv << ebl.attributes.merge(eblt.attributes).merge(user.attributes).values_at(*columns) # picks user.role instead of e_boatlog_team.role
          csv << [ebl.fid, ebl.date_completed, ebl.captain, ebl.dod, ebl.latitude, ebl.longitude, eblt.team, eblt.role, eblt.user.name, ebl.try(:time_in).try(:strftime, "%H:%M"), ebl.try(:time_out).try(:strftime, "%H:%M"), ebl.depth_ft, ebl.hss, ebl.disease, ebl.notes]
        end
      end
    end
  end
end

app/controllers/e_boatlogs_controller.rb
class EBoatlogsController < ApplicationController
	before_action :require_manager

	# Create a new boatlog
	def new
		@eboatlog = EBoatlog.new
    @eboatlog.e_boatlog_teams.build

    respond_to do |format|
  		format.html # new.html.erb
  		format.json { render json: @eboatlog }
  	end
	end

	# Create a new boatlog
	def create
		@eboatlog = EBoatlog.new( e_boatlog_params )

		respond_to do |format|
		  # successful creation
      if @eboatlog.save
        format.html { redirect_to @eboatlog, notice: 'Boatlog successfully created.' }
        format.json { render json: @eboatlog, status: :created, location: @eboatlog }
      # otherwise, print errors
      else
        format.html { render action: "new" }
        format.json { render json: @eboatlog.errors, status: :unprocessable_entity }
      end
    end
	end

	# View all boatlogs
	def index
		@new_eboatlog = EBoatlog.new # use in the view to render a form
		# Admin can view all boatlogs
		if @current_user.role == 'admin'
    	@all_eboatlogs = EBoatlog.order(date_completed: :desc, dod: :desc).all
    # Manager can only view their own boatlogs
    elsif @current_user.role == 'manager'
    	#@boat_logs = BoatLog.where( "boatlog_manager_id=?", current_user.boatlog_manager_id )
    	@all_eboatlogs = EBoatlog.order(date_completed: :desc, dod: :desc).all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eboatlogs }
      format.csv { send_data @all_eboatlogs.as_csv, filename: "ECMP_Boatlogs_#{Date.today}.csv" }
    end
	end

	# View a boatlog
  def show
    @eboatlog = EBoatlog.find(params[:id])
    @eboatlog_teams = @eboatlog.e_boatlog_teams.order(team: :asc, role: :asc).all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @eboatlog }
    end
	end

	# Edit a boatlog
	def edit
		@eboatlog = EBoatlog.find(params[:id])
	end

	# Update the boatlog
	def update
    @eboatlog = EBoatlog.find(params[:id])

    respond_to do |format|
		  # successful update
      if @eboatlog.update(e_boatlog_params)
        format.html { redirect_to @eboatlog, notice: 'Boatlog successfully updated.' }
        format.json { render json: @eboatlog, status: :created, location: @eboatlog }
      # Otherwise, print errors
      else
        format.html { render action: "edit" }
        format.json { render json: @eboatlog.errors, status: :unprocessable_entity }
      end
    end
   end

  # Delete a boatlog
	def destroy 
	  @eboatlog = EBoatlog.find(params[:id])
	  #@eboatlog.destroy
	  # Successful deletion
	  if @eboatlog.destroy
      redirect_to '/e_boatlogs', notice: "Boatlog deleted"
	  # Error occurred
	  else
	  	redirect_to '/e_boatlogs', notice: "Error: boatlog not deleted"
	  end
	end

	private

	def e_boatlog_params
		params.require(:e_boatlog).permit(:fid, :date_completed, :captain, :dod, :latitude, :longitude, :time_in, :time_out, :depth_ft, :hss, :disease, :notes, 
			e_boatlog_teams_attributes: [:id, :team, :user_id, :role, :_destroy])
	end
end

app/views/e_boatlogs/_form.html.erb
<div class="form-horizontal">
	<%= form_for @eboatlog, :html => {:autocomplete => "off"} do |f|%>
	<%= render 'shared/error_messages', :target => @eboatlog %>
		<div class="row">
			<div class="col-md-4">
		    <div class='control-group'>
		      <%= f.label :fid, 'Field ID' %>
		      <%= f.text_field :fid %> 
		    </div>
		  	<div class='control-group'>
			    <%= f.label :date_completed, 'Date Completed' %>
			    <%= f.text_field :date_completed, placeholder: "YYYY-MM-DD" %> 
			  </div>
			  <div class='control-group'>
		      <%= f.label :captain, 'Captain' %>
		      <%= f.text_field :captain %> 
		    </div>
		    <div class='control-group'>
		      <%= f.label :dod, 'Dive of Day (DOD)' %>
		      <%= f.text_field :dod %> 
		    </div>
		    <div class='control-group'>
		      <%= f.label :latitude, 'Latitude' %>
		      <%= f.text_field :latitude %> 
		    </div>
		    <div class='control-group'>
		      <%= f.label :longitude, 'Longitude' %>
		      <%= f.text_field :longitude %> 
		    </div>
		    <div class='control-group'>
			    <%= f.label :time_in, 'Time In' %>
			    <%= f.text_field :time_in, value: f.object.try(:time_in).try(:strftime, "%H:%M"), placeholder: "HH:MM (24 hr clock)", autocomplete: :off, class: 'timeField', id: 'timeIn' %> 
			  </div>
			  <div class='control-group'>
			    <%= f.label :time_out, 'Time Out' %>
			    <%= f.text_field :time_out, value: f.object.try(:time_out).try(:strftime, "%H:%M"), placeholder: "HH:MM (24 hr clock)", autocomplete: :off, class: 'timeField', id: 'timeOut' %> 
			  </div>
			  <div class='control-group'>
		      <%= f.label :depth_ft, 'Depth (ft)' %>
		      <%= f.text_field :depth_ft, class: 'depthField' %> 
		    </div>
		    <div class='control-group'>
		      <%= f.label :hss, 'HSS' %>
		      <%= f.text_field :hss %> 
		    </div>
		    <div class='control-group'>
		      <%= f.label :disease, 'Disease' %>
		      <%= f.text_field :disease %> 
		    </div>
		  </div>
			<div class="col-md-3">
		    <div class='control-group'>
		    	<%= f.label :notes, 'Notes' %>
		    	<%= f.text_area :notes, { :size => '60x4' } %>
		    </div>
	    </div>
    </div>

    <div>
      <h3>Divers</h3>
      <ul class="diverLabels list-inline", style="margin-left:40px">
    		<li class="col-md-2 field">Team</li><li class="col-md-3 field">Diver</li><li class="col-md-2 field">Role</li>
    	</ul>
      <br>
  		<div id='boatlog_teams'>
  			<ol class="diverList">
			    <%= f.fields_for :e_boatlog_teams do |builder| %>
			      <%= render 'team_fields', f: builder %>
			    <% end %>
		      <div class="links">
				     <%= link_to_add_association "Add Diver", f, :e_boatlog_teams, partial: 'team_fields', class: "addDiver" %>
		      </div>
		    </ol>
	     </div>
	   </div>

	  <%= f.submit "Save Boatlog", class: "btn-submit" %>
  <% end %>
</div>

app/views/e_boatlogs/_team_fields.html.erb
<div class='nested-fields'>
	<div class="row">
		<li style="white-space:nowrap;">
		<div class="col-md-2 field">
			<%= f.select :team, ['1','2'], {:include_blank => ""} %> 
		</div>
		<div class="col-md-3 field">
		<%= f.collection_select :user_id, User.where(active: "true").order(name: :asc).all, :id, :name, {:include_blank => ""}, {:class=>"observerSelect" } %>
		</div>
		<div class="col-md-2 field">
			<%= f.select :role, ['A','B'], {:include_blank => ""} %> 
		</div>
		<%= link_to_remove_association "Remove Diver", f, partial: 'team_fields', tabindex: "-1" %>
		</li>
	</div>
</div>

app/views/e_boatlogs/edit.html.erb
<div class="main">
  <div class="container">
  	<h1>Edit ECMP Boatlog</h1>
  	<p><%= button_to 'Cancel', '/e_boatlogs', method: :get, data: { confirm: 'Cancel edit?' } %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/e_boatlogs/index.html.erb
<div class="main">
  <div class="container">
    <%= button_to "New Boatlog", '/e_boatlogs/new', method: :get %>
    <%= button_to "Export CSV", e_boatlogs_path(format: :csv), method: :get %>
    <h1>ECMP Boatlogs</h1>
    <table id="boatlogList", class="display table table-striped table-condensed table-sortable">
      <thead>
        <% #print table header %>
        <tr>
          <th>FID</th>
          <th>Date</th>
          <th>Captain</th>
          <th>DOD</th>
          <th>Time In</th>
          <th>Depth (ft)</th>
          <th>Date Entered</th>
        </tr>
      </thead>
      <tbody>
        <% #print table fields %>
        <% @all_eboatlogs.each do |bl| %>
          <tr data-link="<%=e_boatlog_path(bl.id)%>">
            <td><%= bl.fid %></td>
            <td><%= bl.date_completed %></td>
            <td><%= bl.captain %></td>
            <td><%= bl.dod %></td>
            <td><%= bl.try(:time_in).try(:strftime, "%H:%M") %></td>
            <td><%= bl.depth_ft %></td>
            <td><%= bl.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/e_boatlogs/new.html.erb
<div class="main">
  <div class="container">
  	<h1>New ECMP Boatlog</h1>
  	<p><%= button_to 'Cancel', '/e_boatlogs', method: :get, data: { confirm: 'Cancel new boatlog?' } %></p>
    <%= render 'form' %>
    </div>
</div>

app/views/e_boatlogs/show.html.erb
<div class="container">
<div class='formContainer'>
  <%= button_to "Back to Boatlogs", '/e_boatlogs', method: :get%>
  <%= button_to "New Boatlog", '/e_boatlogs/new', method: :get %>
  <div class="showActions" style="margin-top: 20px">
    <div class="btn-group-vertical">
      <%= button_to('Edit Boatlog', edit_e_boatlog_path(@eboatlog), :method => "get") %>
      <%= button_to('Delete Boatlog', @eboatlog, data: { confirm: 'Are you sure?' }, method: :delete) %>
    </div>
  </div>
  <div id="sampleSection" class="sectionDiv">
  <div class='show_section_1'>
    <div id='section_1_part_1'>

      <dl class="dl-horizontal">
        <dt>FID</dt><dd><%= @eboatlog.fid %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Date Completed</dt><dd><%= @eboatlog.date_completed %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Captain</dt><dd><%= @eboatlog.captain %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Dive of Day</dt><dd><%= @eboatlog.dod %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Latitude</dt><dd><%= @eboatlog.latitude %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Longitude</dt><dd><%= @eboatlog.longitude %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Time In</dt><dd><%= @eboatlog.try(:time_in).try(:strftime, "%H:%M")%></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Time Out</dt><dd><%= @eboatlog.try(:time_out).try(:strftime, "%H:%M") %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Depth (ft)</dt><dd><%= @eboatlog.depth_ft %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>HSS</dt><dd><%= @eboatlog.hss %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Disease</dt><dd><%= @eboatlog.disease %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Notes</dt><dd><%= @eboatlog.notes %></dd>
      </dl>
    </div>

    <div id='section_1_part_2'>
      <h2>Divers</h2>
      <table id="boatlogSurveyList", class="display table table-striped" style="width: auto">
        <thead>
          <% #print table header %>
          <tr>
            <th>Team</th>
            <th>Diver</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody>
          <% @eboatlog_teams.each do |bt|  %>
            <tr>
              <td><%= bt.team %></td>
              <td><%= User.find(bt.user_id).name %></td>
              <td><%= bt.role %></td>
            </tr>   
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>
</div>