config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#home'

  # Navigation
  get '/home' => 'static_pages#home'
  get '/login' => 'sessions#new'
  get '/about' => 'static_pages#about'
  get '/userhome' => 'static_pages#userhome'

  # Authentication
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy' 

  # User management
  get '/users' => 'users#index'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  get '/users/edit' => 'users#edit'
  post '/users/edit' => 'users#update'

  # Manager management
  get '/managers' => 'managers#index'
  get '/managers/new' => 'managers#new'
  post '/managers/new' => 'managers#create'
  get '/managers/edit' => 'managers#edit'
  post '/managers/edit' => 'managers#update'

  # Boatlog management
  #get '/boatlogs' => 'boatlogs#index'
  post '/boatlogs/:id' => 'boatlogs#show'
  #get '/boatlogs/new' => 'boatlogs#new'
  #post '/boatlogs/new' => 'boatlogs#create'
  #get '/boatlogs/edit' => 'boatlogs#edit'
  #post '/boatlogs/edit' => 'boatlogs#update'

  # Dashboard
  get '/dashboard' => 'dashboard#show'

  # Field Progress
  get '/sites' => 'sites#index'
  post '/sites/:id' => 'sites#show'

  # Surveys
  post '/fish_transects/:id' => 'fish_transects#show'
  get '/diademas' => 'diademas#index'
  get '/e_plots' => 'e_plots#index'
  get '/e_plot_corals' => 'e_plot_corals#index'
  get '/e_esa_pas' => 'e_esa_pas#index'

  # IDs
  get '/coral_codes' => 'coral_codes#index'

  # Resources
  resources :users
  resources :managers
  resources :boatlogs
  resources :sites
  resources :fish_transects
  resources :fish_rovers
  resources :algae_heights
  resources :coral_healths
  resources :e_boatlogs
  resources :e_surveys

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/algae_height.rb
require 'csv'

class AlgaeHeight < ApplicationRecord
  validates_presence_of :site, :manager, :user, :date_completed, :rep

  belongs_to :user

  belongs_to :site
  accepts_nested_attributes_for :site

  belongs_to :manager
  accepts_nested_attributes_for :manager

  has_many :transect_algaes, :dependent => :destroy, inverse_of: :algae_height
  accepts_nested_attributes_for :transect_algaes, :reject_if => :all_blank, :allow_destroy => true

  has_many :algaes, through: :transect_algaes
  accepts_nested_attributes_for :algaes

  def self.as_csv
    columns = %w(algae_height_id proofed site_name date_completed name rep notes code_name full_name height_cm)
    CSV.generate(headers: true) do |csv|
      csv << columns.map(&:humanize)
      all.each do |algae_height|
        site = algae_height.site
        user = algae_height.user
        algae_height.transect_algaes.each do |transect_algae|
          algae = transect_algae.algae
          csv << algae_height.attributes.merge(site.attributes).merge(user.attributes).merge(transect_algae.attributes).merge(algae.attributes).values_at(*columns)
        end
      end
    end
  end
end

app/controllers/algae_heights_controller.rb
class AlgaeHeightsController < ApplicationController
  before_action :require_user

  def new
    @aht = AlgaeHeight.new
    @aht.transect_algaes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aht }
    end
  end

  def create
    @aht = AlgaeHeight.new( algae_height_params )

    respond_to do |format|
      # successful creation
      if @aht.save
        format.html { redirect_to @aht, notice: 'Algae heights successfully created.' }
        format.json { render json: @aht, status: :created, location: @aht }
      # otherwise, print errors
      else
        format.html { render action: "new" }
        format.json { render json: @aht.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @new_aht = AlgaeHeight.new # use in the view to render a form
    # Only show transects
    if @current_user.manager?
      @aht = AlgaeHeight.order(date_completed: :asc, site_id: :asc, rep: :asc).all
      @filename = "all"
    else
      @aht = @current_user.algae_heights.order(date_completed: :asc, site_id: :asc, rep: :asc).all
      @filename = @current_user.name
    end

    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data @aht.as_csv, filename: "AlgaeHeights_#{@filename}_#{Date.today}.csv" }
    end
  end
  
  def show
    @new_aht = AlgaeHeight.new # use in the view to render a form
    
    @aht = AlgaeHeight.find(params[:id])
    @tranas = @aht.transect_algaes.all

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def edit
    @aht = AlgaeHeight.find(params[:id])
  end

  def update
    @aht = AlgaeHeight.find(params[:id])

    respond_to do |format|
      # successful update
      if @aht.update(algae_height_params)
        format.html { redirect_to @aht, notice: 'Algae heights successfully updated.' }
        format.json { render json: @aht, status: :created, location: @aht }
      # Otherwise, print errors
      else
        format.html { render action: "edit" }
        format.json { render json: @aht.errors, status: :unprocessable_entity }
      end
    end
   end

   def destroy 
    @aht = AlgaeHeight.find(params[:id])
    #@boatlog.destroy
    # Successful deletion
    if @aht.destroy
      redirect_to '/algae_heights', notice: "Algae heights deleted"
    # Error occurred
    else
      redirect_to '/algae_heights', notice: "Error: algae heights not deleted"
    end
  end

  private

  def algae_height_params
    params.require(:algae_height).permit(:manager_id, :site_id, :user_id, :date_completed, :rep, :notes, :proofed, 
      transect_algaes_attributes: [:id, :algae_id, :height_cm, :_destroy])
  end
end

app/views/algae_heights/_algae_fields.html.erb
<div class='nested-fields'>
	<div class="row algaeRow">
		<li>
		<div class="col-md-3 field">
			<%= f.collection_select :algae_id, Algae.order(occurrence: :asc).all, :id, :combo_name, {:include_blank => ""}, {:class=>"speciesSelect select2-container" } %> 
		</div>
		<div class="col-md-1 field">
			<%= f.text_field :height_cm, { :size => '3', :class=>"heightField"} %>
		</div>
		<%= link_to_remove_association "Remove Algae", f, partial: 'algae_fields', tabindex: "-1" %>
		</li>
	</div>
</div>

app/views/algae_heights/_form.html.erb
<div class="form-horizontal">
	<%= form_for @aht, :html => {:autocomplete => "off"} do |f|%>
	<%= render 'shared/error_messages', :target => @aht %>
		<div class="row">
			<div class="col-md-4">
				<div class='control-group'>
					<%= f.label :proofed, 'Proofed?' %>
		      <%= f.check_box :proofed %> 
				</div>
				<div class='control-group'>
		      <%= f.label :manager_id, 'Project' %>
		      <%= f.collection_select :manager_id, Manager.all, :id, :project, {:include_blank => ""} %> 
		    </div>
		    <div class='control-group'>
			    <%= f.label :site_id, 'Site Name' %>
			    <%= f.collection_select :site_id, Site.all, :id, :combo_name, {:include_blank => ""}, {:class=>"metaSelect" } %> 
		  	</div>
		  	<div class='control-group'>
			    <%= f.label :user_id, 'Observer' %>
			    <%= f.collection_select :user_id, User.where(active: "true").order(name: :asc).all, :id, :name, {:include_blank => ""}, {:class=>"metaSelect" } %> 
		  	</div>
		  	<div class='control-group'>
			    <%= f.label :date_completed, 'Date Completed' %>
			    <%= f.text_field :date_completed, placeholder: "YYYY-MM-DD" %> 
			  </div>
			  <div class="control-group">
					<%= f.label :rep, 'Transect' %>
					<%= f.text_field :rep, { :size => '3' } %>
				</div>
		  </div>

			<div class="col-md-3">
		    <div class='control-group'>
		    	<%= f.label :notes, 'Notes' %>
		    	<%= f.text_area :notes, { :size => '60x4' } %>
		    </div>
	    </div>
    </div>

    <div>
      <h3>Algae</h3>
      <p>If there was no algae on the transect, please select "NOALGAE" and give it a height of 0.</p>
      <div class="algaeLabels">
      	<ul class="list-inline">
      		<li class="col-md-3"> Algae Type</li><li class="col-md-1">Height (cm)</li><li class="col-8"> </li>
      	</ul>
      </div>
      <br>
  		<div id='algaes'>
  			<ol class="algaeList">
			    <%= f.fields_for :transect_algaes do |builder| %>
			      <%= render 'algae_fields', f: builder %>
			    <% end %>
		      <div class="links">
				     <%= link_to_add_association "Add Algae", f, :transect_algaes, partial: 'algae_fields', class: "addAlgae" %>
		      </div>
		    </ol>
	     </div>
	   </div>

	  <%= f.submit "Save Algae Heights", class: "btn-submit", tabindex: "-1", style: "margin-top:50px;margin-bottom:100px" %>
  <% end %>
</div>

app/views/algae_heights/edit.html.erb
<div class="main">
  <div class="container">
    <h1>Edit Algae Heights</h1>
    <p><%= button_to 'Cancel', '/algae_heights', method: :get, data: { confirm: 'Cancel edit?' } %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/algae_heights/index.html.erb
<div class="main">
  <div class="container">
    <%= button_to "New Algae Heights Transect", '/algae_heights/new', method: :get %>
    <%= button_to "Export CSV", algae_heights_path(:format => :csv), method: :get %>
    <h1>Algae Heights</h1>
    <table class="display table table-striped table-condensed table-sortable">
      <thead>
        <% #print table header %>
        <tr>
          <th>Diver</th>
          <th>Site</th>
          <th>Date</th>
          <th>Replicate</th>
          <th>Date Entered</th>
          <th>Proofed?</th>
        </tr>
      </thead>
      <tbody>
        <% #print table fields %>
        <% @aht.each do |ah| %>
          <tr data-link="<%=algae_height_path(ah.id)%>">
            <td><%= ah.user.name %></td>
            <td><%= ah.site.site_name %></td>
            <td><%= ah.date_completed %></td>
            <td><%= ah.rep %></td>
            <td><%= ah.created_at %></td>
            <td><%= ah.proofed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/algae_heights/new.html.erb
<div class="main">
  <div class="container">
    <h1>New Algae Height Transect</h1>
    <p><%= button_to 'Cancel', '/algae_heights', method: :get, data: { confirm: 'Cancel new algae height transect?' } %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/algae_heights/show.html.erb
<div class="container">
	<div class='formContainer'>
		<%= button_to "Back to Algae Heights", '/algae_heights', method: :get%>
    <%= button_to "New Algae Heights Transect", '/algae_heights/new', method: :get %>
		<div class="showActions" style="margin-top: 20px">
    <div class="btn-group-vertical">
      <%= button_to('Edit Algae Heights', edit_algae_height_path(@aht), :method => "get") %>
      <%= button_to('Delete Algae Heights', @aht, data: { confirm: 'Are you sure?' }, method: :delete) %>
    </div>
  </div>
  <div id="sampleSection" class="sectionDiv">
  <div class='show_section_1'>
    <div id='section_1'>

      <dl class="dl-horizontal">
        <dt>Proofed?</dt><dd><%= @aht.proofed %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Project</dt><dd><%= @aht.manager.project %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Observer</dt><dd><%= @aht.user.name %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Site</dt><dd><%= @aht.site.site_name %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Sample Date</dt><dd><%= @aht.date_completed %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Replicate</dt><dd><%= @aht.rep %></dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Notes</dt><dd><%= @aht.notes %></dd>
      </dl>
    </div>

    <div id='section_2'>
      <h2>Algae</h2>
      <table id="AlgaeList", class="display table table-striped" style="width: auto">
        <thead>
          <% #print table header %>
          <tr>
          	<th>Algae Type</th>
            <th>Height(cm)</th>
          </tr>
        </thead>
        <tbody>
          <% @tranas.each do |a|  %>
            <tr>
            	<td><%= a.algae.combo_name %></td>
              <td><%= a.height_cm %></td>
            </tr>   
          <% end %>
        </tbody>
      </table>
    </div>
	</div>
</div>